import { Request, Response } from 'express';
import { google } from 'googleapis';
import { config } from '../../../config/env';
import { GlobalSettings } from '../models/GlobalSettings';
import { logger } from '../../../config/logger';
import { createCustomGoogleCalendarEvent } from '../../../utils/integrations';

const oauth2Client = new google.auth.OAuth2(
  config.googleClientId,
  config.googleClientSecret,
  config.googleRedirectUri
);

export const getGoogleOAuthUrl = async (req: Request, res: Response) => {
  try {
    const scopes = [
      'https://www.googleapis.com/auth/calendar.events',
      'https://www.googleapis.com/auth/userinfo.email',
      'https://www.googleapis.com/auth/userinfo.profile'
    ];

    const url = oauth2Client.generateAuthUrl({
      access_type: 'offline', // Request a refresh token
      prompt: 'consent', // Force consent prompt to guarantee refresh token
      scope: scopes,
      state: 'google'
    });

    res.status(200).json({ success: true, data: { url } });
  } catch (error) {
    logger.error('Failed to generate Google OAuth URL', error);
    res.status(500).json({ success: false, error: { message: 'Failed to generate OAuth URL' } });
  }
};

export const handleGoogleCallback = async (req: Request, res: Response) => {
  try {
    const { code } = req.body;
    
    if (!code) {
      return res.status(400).json({ success: false, error: { message: 'Authorization code is required' } });
    }

    // Exchange the authorization code for an access token and refresh token
    const { tokens } = await oauth2Client.getToken(code);
    
    const globalSettings = await GlobalSettings.findOne() || new GlobalSettings();
    
    globalSettings.googleWorkspaceConnected = true;
    globalSettings.googleAccessToken = tokens.access_token || undefined;
    if (tokens.refresh_token) {
      globalSettings.googleRefreshToken = tokens.refresh_token;
    }
    
    await globalSettings.save();

    res.status(200).json({ success: true, data: { message: 'Google Workspace connected successfully' } });
  } catch (error: any) {
    logger.error('Google Callback Error', error);
    res.status(500).json({ success: false, error: { message: error.message || 'Failed to complete Google OAuth handshake' } });
  }
};

export const testGoogleCalendarEvent = async (req: Request, res: Response) => {
  try {
    const settings = await GlobalSettings.findOne();
    if (!settings || !settings.googleWorkspaceConnected || (!settings.googleRefreshToken && !settings.googleAccessToken)) {
      return res.status(400).json({ success: false, error: { message: 'Google Workspace is not fully connected. Please reconnect.' } });
    }

    // Setup client with stored tokens
    const client = new google.auth.OAuth2(config.googleClientId, config.googleClientSecret);
    client.setCredentials({
      access_token: settings.googleAccessToken,
      refresh_token: settings.googleRefreshToken
    });

    const calendar = google.calendar({ version: 'v3', auth: client });
    
    // Create a 30-minute test event starting tomorrow
    const startTime = new Date();
    startTime.setDate(startTime.getDate() + 1);
    const endTime = new Date(startTime.getTime() + 30 * 60000);

    const event = {
      summary: 'Test WorkSphere HRMS Sync',
      description: 'This is an automated test event generated by your WorkSphere HRMS integration.',
      start: {
        dateTime: startTime.toISOString(),
      },
      end: {
        dateTime: endTime.toISOString(),
      },
    };

    await calendar.events.insert({
      calendarId: 'primary',
      requestBody: event,
    });

    res.status(200).json({ success: true, data: { message: 'Test calendar event created successfully' } });
  } catch (error: any) {
    logger.error('Failed to create test calendar event', error);
    res.status(500).json({ success: false, error: { message: error.message || 'Failed to create test calendar event' } });
  }
};

export const disconnectGoogleWorkspace = async (req: Request, res: Response) => {
  try {
    const settings = await GlobalSettings.findOne();
    if (settings) {
      settings.googleWorkspaceConnected = false;
      settings.googleAccessToken = undefined;
      settings.googleRefreshToken = undefined;
      await settings.save();
    }
    
    res.status(200).json({ success: true, data: { message: 'Google Workspace disconnected successfully' } });
  } catch (error) {
    logger.error('Failed to disconnect Google Workspace', error);
    res.status(500).json({ success: false, error: { message: 'Failed to disconnect Google Workspace' } });
  }
};

export const createCustomCalendarEvent = async (req: Request, res: Response) => {
  try {
    const { summary, description, startTime, endTime, attendees, location } = req.body;
    
    if (!summary || !startTime || !endTime) {
      return res.status(400).json({ success: false, error: { message: 'Summary, startTime, and endTime are required' } });
    }

    await createCustomGoogleCalendarEvent(
      summary,
      description || '',
      new Date(startTime),
      new Date(endTime),
      location,
      attendees
    );

    res.status(200).json({ success: true, data: { message: 'Event created successfully' } });
  } catch (error: any) {
    logger.error('Failed to create custom calendar event', error);
    res.status(500).json({ success: false, error: { message: error.message || 'Failed to create event' } });
  }
};

export const getPersonalGoogleUrl = async (req: Request, res: Response) => {
  try {
    const scopes = [
      'https://www.googleapis.com/auth/calendar.events',
      'https://www.googleapis.com/auth/userinfo.email',
      'https://www.googleapis.com/auth/userinfo.profile'
    ];

    const url = oauth2Client.generateAuthUrl({
      access_type: 'offline', // Request a refresh token
      prompt: 'consent', // Force consent prompt to guarantee refresh token
      scope: scopes,
      state: 'personal-google'
    });

    res.status(200).json({ success: true, data: { url } });
  } catch (error) {
    logger.error('Failed to generate personal Google OAuth URL', error);
    res.status(500).json({ success: false, error: { message: 'Failed to generate OAuth URL' } });
  }
};

export const handlePersonalGoogleCallback = async (req: Request, res: Response) => {
  try {
    const { code } = req.body;
    if (!code) {
      return res.status(400).json({ success: false, error: { message: 'Authorization code is required' } });
    }

    const { tokens } = await oauth2Client.getToken(code);
    
    const user = (req as any).user;
    if (!user.integrations) user.integrations = {};
    if (!user.integrations.google) user.integrations.google = {};
    
    user.integrations.google.connected = true;
    user.integrations.google.accessToken = tokens.access_token || undefined;
    if (tokens.refresh_token) {
      user.integrations.google.refreshToken = tokens.refresh_token;
    }
    
    await user.save();

    res.status(200).json({ success: true, data: { message: 'Personal Google Calendar connected successfully' } });
  } catch (error: any) {
    logger.error('Personal Google Callback Error', error);
    res.status(500).json({ success: false, error: { message: error.message || 'Failed to complete Google OAuth handshake' } });
  }
};

export const testPersonalGoogleEvent = async (req: Request, res: Response) => {
  try {
    const user = (req as any).user;
    const googleSettings = user.integrations?.google;

    if (!googleSettings || !googleSettings.connected || (!googleSettings.refreshToken && !googleSettings.accessToken)) {
      return res.status(400).json({ success: false, error: { message: 'Personal Google Workspace is not fully connected. Please reconnect.' } });
    }

    const client = new google.auth.OAuth2(config.googleClientId, config.googleClientSecret);
    client.setCredentials({
      access_token: googleSettings.accessToken,
      refresh_token: googleSettings.refreshToken
    });

    const calendar = google.calendar({ version: 'v3', auth: client });
    
    const startTime = new Date();
    startTime.setDate(startTime.getDate() + 1);
    const endTime = new Date(startTime.getTime() + 30 * 60000);

    const event = {
      summary: 'Test Personal WorkSphere HRMS Sync',
      description: 'This is an automated test event generated by your personal WorkSphere HRMS integration.',
      start: {
        dateTime: startTime.toISOString(),
      },
      end: {
        dateTime: endTime.toISOString(),
      },
    };

    await calendar.events.insert({
      calendarId: 'primary',
      requestBody: event,
    });

    res.status(200).json({ success: true, data: { message: 'Test calendar event created successfully on your personal calendar' } });
  } catch (error: any) {
    logger.error('Failed to create personal test event', error);
    res.status(500).json({ success: false, error: { message: error.message || 'Failed to create test calendar event' } });
  }
};

export const disconnectPersonalGoogle = async (req: Request, res: Response) => {
  try {
    const user = (req as any).user;
    if (user.integrations && user.integrations.google) {
      user.integrations.google.connected = false;
      user.integrations.google.accessToken = undefined;
      user.integrations.google.refreshToken = undefined;
      await user.save();
    }
    
    res.status(200).json({ success: true, data: { message: 'Personal Google Workspace disconnected successfully' } });
  } catch (error) {
    logger.error('Failed to disconnect personal Google Workspace', error);
    res.status(500).json({ success: false, error: { message: 'Failed to disconnect personal Google Workspace' } });
  }
};
